Initiatives/Controllers/InventoryController.cs
using Initiatives.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Initiatives.Controllers
{
    public class ValidateAjaxAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (!filterContext.HttpContext.Request.IsAjaxRequest())
                return;

            var modelState = filterContext.Controller.ViewData.ModelState;
            var InvAddNewReq = filterContext.ActionParameters.Values.FirstOrDefault() as InventoryDetailInfo;
            var getValidationAddNewStock = filterContext.HttpContext.Session["AddNewStock"].ToString();
            var getValidationAddNewReq = filterContext.HttpContext.Session["AddNewReq"].ToString();

            if (InvAddNewReq != null && getValidationAddNewStock == "True")
            {
                modelState.Remove("");
            }

            if (InvAddNewReq != null && getValidationAddNewReq == "True")
            {
                modelState.Remove("Supplier");
                if (InvAddNewReq.RequestQuantity > InvAddNewReq.AvailableQuantity)
                {
                    modelState.AddModelError("RequestQuantity", "Request quantity cannot exceed available quantity.");
                }
            }

            if (!modelState.IsValid)
            {
                var errorModel =
                        from x in modelState.Keys
                        where modelState[x].Errors.Count > 0
                        select new
                        {
                            key = x,
                            errors = modelState[x].Errors.
                                                          Select(y => y.ErrorMessage).
                                                          ToArray()
                        };
                filterContext.Result = new JsonResult()
                {
                    Data = new
                    {
                        success = false,
                        exception = false,
                        data = errorModel
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
                //filterContext.HttpContext.Response.StatusCode = 200;
            }
        }
    }
    public class InventoryController : Controller
    {
        //
        // GET: /Inventory/
        private OpportunityManagementEntities db = new OpportunityManagementEntities();

        [Authorize]
        public ActionResult Index()
        {
            MainModel model = new MainModel
            {
                InventoryListTable = (from m in db.PartNo_Items
                                          //join n in db.InventoryOuts on m.partNo equals n.partNo into p
                                          //join o in db.InventoryIns on m.partNo equals o.partNo into q
                                      select new InventoryDetailInfo()
                                      {
                                          PartNo = m.partNo,
                                          MaterialCode = m.materialNo,
                                          MaterialDesc = m.description,
                                          AvailableBalance = m.availableBalance,
                                          BalanceReserved = m.balanceReserved
                                      }).ToList()
            };

            return View(model);
        }

        [Authorize]
        public ActionResult AddNewStock()
        {
            var MaterialNoQuery = db.PartNo_Items.Select(c => new { PartNo = c.partNo, MaterialCode = c.materialNo })
                    .OrderBy(c => c.MaterialCode);
            var ItemTypeQuery = db.InvItemTypes.Select(c => new { ItemTypeId = c.itemTypeId, ItemType = c.itemType })
                    .OrderBy(c => c.ItemType);
            ViewBag.MaterialNolist = new SelectList(MaterialNoQuery.AsEnumerable(), "PartNo", "MaterialCode" /*,model.DODetailObject.BranchId*/);
            ViewBag.ItemTypelist = new SelectList(ItemTypeQuery.AsEnumerable(), "ItemTypeId", "ItemType" /*model.DODetailObject.BranchId*/);
            Session["AddNewStock"] = "True"; Session["AddNewReq"] = "False";

            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAjax]
        public ActionResult AddNewStock(InventoryDetailInfo model)
        {
            try
            {
                InventoryIn _objInventoryIn = new InventoryIn
                {
                    uuid = Guid.NewGuid(),
                    partNo = model.PartNo,
                    inDate = model.ReceivedDate,
                    inQuantity = model.QuantityReceived,
                    UOM = model.UOM,
                    unitPrice = model.UnitPrice,
                    itemTypeId = model.ItemTypeId,
                    supplier = model.Supplier,
                    purchasePONo = model.PurchasePONo
                };
                db.InventoryIns.Add(_objInventoryIn);
                db.SaveChanges();

                int inQuantity = 0; int outQuantity = 0;
                var inQuantityQuery = db.InventoryIns.Where(x => x.partNo == model.PartNo).ToList();
                var outQuantityQuery = db.InventoryOuts.Where(x => x.partNo == model.PartNo).ToList();

                if (inQuantityQuery != null)
                {
                    foreach (var item in inQuantityQuery)
                    {
                        inQuantity += item.inQuantity;
                    }
                }

                if (outQuantityQuery != null)
                {
                    foreach (var item in outQuantityQuery)
                    {
                        outQuantity += item.outQuantity;
                    }
                }

                PartNo_Items updateinQuantity = db.PartNo_Items.Where(x => x.partNo == model.PartNo).First();
                updateinQuantity.inQuantity = inQuantity;
                updateinQuantity.availableBalance = inQuantity - outQuantity;
                db.SaveChanges();

                return Json(new { success = true });
            }
            catch(DbEntityValidationException e)
            {
                StringWriter ExMessage = new StringWriter();
                foreach (var eve in e.EntityValidationErrors)
                {
                    ExMessage.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        ExMessage.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                ExMessage.Close();
                return Json(new { success = false, exception = true, message = ExMessage.ToString() });
            }            
        }

        [Authorize]
        public ActionResult AddNewReq()
        {
            var MaterialNoQuery = db.PartNo_Items.Select(c => new { PartNo = c.partNo, MaterialCode = c.materialNo, AvailableBalance = c.availableBalance }).Where(c => c.AvailableBalance != 0)
                    .OrderBy(c => c.MaterialCode);
            var DONoQuery = db.DeliveryOrders.Select(c => new { DOId = c.DOId, DONo = c.DONo })
                    .OrderBy(c => c.DONo);
            var StatusQuery = db.InvStatus.Select(c => new { StatusId = c.statusId, Status = c.status })
                    .OrderBy(c => c.Status);
            var ProjectQuery = db.Opportunities.Select(c => new { ProjectId = c.opportunityId, Project = c.name }).OrderBy(c => c.Project);
            var PONoQuery = db.PurchaseOrders.Select(c => new { POId = c.POId, PONo = c.Details_PONo }).OrderBy(c => c.PONo);
            ViewBag.MaterialNolist = new SelectList(MaterialNoQuery.AsEnumerable(), "PartNo", "MaterialCode" /*,model.DODetailObject.BranchId*/);
            ViewBag.Project = new SelectList(ProjectQuery.AsEnumerable(), "ProjectId", "Project");
            ViewBag.ProjectPONo = new SelectList(PONoQuery.AsEnumerable(), "POId", "PONo");
            ViewBag.DeliveryOrderNo = new SelectList(DONoQuery.AsEnumerable(), "DOId", "DONo" /*,model.DODetailObject.BranchId*/);
            ViewBag.Status = new SelectList(StatusQuery.AsEnumerable(), "StatusId", "Status" /*,model.DODetailObject.BranchId*/);
            Session["AddNewReq"] = "True"; Session["AddNewStock"] = "False";

            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAjax]
        public ActionResult AddNewReq(InventoryDetailInfo model)
        {
            try
            {
                InventoryOut _objInventoryOut = new InventoryOut
                {
                    uuid = Guid.NewGuid(),
                    partNo = model.PartNo,
                    outDate = model.OutDate,
                    outQuantity = model.RequestQuantity,
                    POId = model.POId,
                    requestById = Int32.Parse(Session["UserId"].ToString()),
                    DOId = model.DOId,
                    statusId = model.StatusId,
                    remark = model.Remark
                };
                db.InventoryOuts.Add(_objInventoryOut);
                db.SaveChanges();

                PartNo_Items updateItems = db.PartNo_Items.Where(x => x.partNo == model.PartNo).First();
                updateItems.outQuantity = updateItems.outQuantity + model.RequestQuantity;
                db.SaveChanges();

                updateItems.availableBalance = updateItems.inQuantity - updateItems.outQuantity;
                db.SaveChanges();

                if (model.StatusId == 1)
                {
                    int balanceReservedQuantity = 0;

Initiatives/Views/Inventory/AddNewReq.cshtml
@{ Layout = "~/Views/Shared/_MainLayout.cshtml"; }
@model Initiatives.Models.InventoryDetailInfo

<div id="AddNewReq" class="container-fluid">
    <div class="clearfix margin-bottom-30"></div>
    <button id="btn-BackDo" class="btn-u btn-success margin-bottom-25" type="button">
        <i class="fa fa-tags"></i> Back
    </button>
    <div id="CreateNewPO-1">
        <div class="clearfix margin-bottom-10"></div>
        @using (Html.BeginForm("AddNewReq", "Inventory", FormMethod.Post, new { @id = "AddNewReqForm", @class = "sky-form" }))
        {
            <div class="panel panel-u margin-bottom-20">
                <div class="panel-heading margin-bottom-10">
                    <h3 class="panel-title"><i class="fa fa-user"></i> Add New Request</h3>
                </div>
                <div class="panel-body">
                    <div class="shadow-wrapper">
                        <div class="tag-box tag-box-v1 box-shadow shadow-effect-2">
                            <div class="row">
                                <div class="container">
                                    <h4><b>General Information</b></h4>
                                </div>
                                <div class="clearfix margin-bottom-10"></div>
                                <div class="col-md-6">
                                    <section>
                                        <label for="MaterialCode" class="col-lg-3 control-label">Material Code</label>
                                        <label class="select">
                                            @Html.DropDownListFor(m => m.PartNo, (IEnumerable<SelectListItem>)ViewBag.MaterialNolist, "Please select material no here", new { @id = "NewReqMaterialCode", @class = "form-control-static" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.PartNo, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="MaterialDescription" class="col-lg-3 control-label">Material Description</label>
                                        @Html.TextBoxFor(m => m.MaterialDesc, new { @id = "MaterialDescription", @class = "form-control", @type = "text", @disabled = "disabled" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.MaterialDesc, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="AvailableQuantity" class="col-lg-3 control-label">Available Quantity</label>
                                        @Html.TextBoxFor(m => m.AvailableQuantity, new { @id = "AvailableQuantity", @class = "form-control", @type = "text", @disabled = "disabled" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.AvailableQuantity, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="RequestQuantity" class="col-lg-3 control-label">Request Quantity</label>
                                        @Html.TextBoxFor(m => m.RequestQuantity, new { @id = "RequestQuantity", @class = "form-control", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.RequestQuantity, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="Project" class="col-lg-3 control-label">Project</label>
                                        <label class="select">
                                            @Html.DropDownListFor(m => m.ProjectId, (IEnumerable<SelectListItem>)ViewBag.Project,"Please select project here", new { @id = "Project", @class = "form-control-static" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.ProjectId, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="ProjectPONo" class="col-lg-3 control-label">Project PO No.</label>
                                        <label class="select">
                                            @Html.DropDownListFor(m => m.POId, (IEnumerable<SelectListItem>)ViewBag.ProjectPONo, "Please select PO no here", new { @id = "ProjectPONo", @class = "form-control-static" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.POId, null, new { @class = "note-error color-red" })
                                    </section>
                                </div>
                                <div class="col-md-6">                                   
                                    <section>
                                        <label for="OutDate" class="col-lg-3 control-label">Out Date</label>
                                        <label class="col-lg-offset-5 input">
                                            <i class="icon-append fa fa-calendar"></i>
                                            @Html.TextBoxFor(m => m.OutDate, "{0:dd/MM/yyyy}", new { @id = "OutDate", @class = "datepicker", @type = "text" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.OutDate, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="DeliveryOrderNo" class="col-lg-3 control-label">Delivery Order No.</label>
                                        <label class="select">
                                            @Html.DropDownListFor(m => m.DOId, (IEnumerable<SelectListItem>)ViewBag.DeliveryOrderNo, "Please select DO no here", new { @id = "DeliveryOrderNo", @class = "form-control-static" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.DOId, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="Status" class="col-lg-3 control-label">Status</label>
                                        <label class="select">
                                            @Html.DropDownListFor(m => m.StatusId, (IEnumerable<SelectListItem>)ViewBag.Status, "Please select status here", new { @id = "Status", @class = "form-control-static" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.StatusId, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="Remark" class="col-lg-3 control-label">Remark</label>
                                        <label class="col-lg-offset-5 textarea textarea-resizable">
                                            @Html.TextAreaFor(m => m.Remark, 3, 1, new { @id = "Remark" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.Remark, null, new { @class = "note-error color-red" })
                                    </section>
                                </div>
                                @*<div class="clearfix margin-bottom-20"></div>*@
                            </div>
                        </div>
                    </div>
                    <button id="btn-SubmitNewReq" type="button" class="btn-u btn-u-primary btn-FloatRight">Submit</button>
                </div>
            </div>

            <div class="modal fade bs-example-modal-sm" id="AddNewRequestLoading" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                    <img class="img-responsive" src="~/Images/ajax_loader.gif" alt="Loading ..." />
                </div>
            </div>
        }
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var UrlSubmitNewReq = "@Url.Action("AddNewReq", "Inventory")";
        var UrlProjectInfo = "@Url.Action("GetProjectInfo", "Inventory")";
        var UrlPartNoInfo = "@Url.Action("GetPartNoInfo", "Inventory")";
        var UrlContractList = "@Url.Action("ContractList", "ContList" )";
    </script>
    @Scripts.Render("~/bundles/JSPages");
}

Initiatives/Views/Inventory/AddNewStock.cshtml
@{ Layout = "~/Views/Shared/_MainLayout.cshtml"; }
@model Initiatives.Models.InventoryDetailInfo

<div id="newPO" class="container-fluid">
    <div class="clearfix margin-bottom-30"></div>
    <button id="btn-BackAddNewStock" class="btn-u btn-success margin-bottom-25" type="button">
        <i class="fa fa-tags"></i> Back
    </button>
    <div id="CreateNewPO-1">
        <div class="clearfix margin-bottom-10"></div>
        @using (Html.BeginForm("AddNewStock", "POList", FormMethod.Post, new { @id = "AddNewStockForm", @class = "sky-form" }))
        {
            <div class="panel panel-u margin-bottom-20">
                <div class="panel-heading margin-bottom-10">
                    <h3 class="panel-title"><i class="fa fa-user"></i> Add New Stock</h3>
                </div>
                <div class="panel-body">
                    <div class="shadow-wrapper">
                        <div class="tag-box tag-box-v1 box-shadow shadow-effect-2">
                            <div class="row">
                                <div class="container">
                                    <h4><b>General Information</b></h4>
                                </div>
                                <div class="clearfix margin-bottom-10"></div>
                                <div class="col-md-6">
                                    <section>
                                        <label for="MaterialCode" class="col-lg-3 control-label">Material Code</label>
                                        <label class="select">
                                            @Html.DropDownListFor(m => m.PartNo, (IEnumerable<SelectListItem>)ViewBag.MaterialNolist, "Please select material no here", new { @id = "NewStockMaterialCode", @class = "form-control-static" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.PartNo, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="MaterialDescription" class="col-lg-3 control-label">Material Description</label>
                                        @Html.TextBoxFor(m => m.MaterialDesc, new { @id = "MaterialDescription", @class = "form-control", @type = "text", @disabled = "disabled" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.MaterialDesc, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="ReceivedDate" class="col-lg-3 control-label">Received Date</label>
                                        <label class="col-lg-offset-5 input">
                                            <i class="icon-append fa fa-calendar"></i>
                                            @Html.TextBoxFor(m => m.ReceivedDate, "{0:dd/MM/yyyy}", new { @id = "ReceivedDate", @class = "datepicker", @type = "text" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.ReceivedDate, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="QuantityReceived" class="col-lg-3 control-label">Quantity Received</label>
                                        @Html.TextBoxFor(m => m.QuantityReceived, new { @id = "QuantityReceived", @class = "form-control", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.QuantityReceived, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="UOM" class="col-lg-3 control-label">Unit of Material</label>
                                        @Html.TextBoxFor(m => m.UOM, new { @id = "UOM", @class = "form-control", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.UOM, null, new { @class = "note-error color-red" })
                                    </section>
                                </div>
                                <div class="col-md-6">
                                    <section>
                                        <label for="UnitPrice" class="col-lg-3 control-label">Unit Price</label>
                                        @Html.TextBoxFor(m => m.UnitPrice, new { @id = "UnitPrice", @class = "form-control", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.UnitPrice, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="ItemType" class="col-lg-3 control-label">Item Type</label>
                                        <label class="select">
                                            @Html.DropDownListFor(m => m.ItemTypeId, (IEnumerable<SelectListItem>)ViewBag.ItemTypelist, "Please select item type here", new { @id = "ItemType", @class = "form-control-static" })
                                        </label>
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.ItemTypeId, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="Supplier" class="col-lg-3 control-label">Supplier</label>
                                        @Html.TextBoxFor(m => m.Supplier, new { @id = "Supplier", @class = "form-control", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.Supplier, null, new { @class = "note-error color-red" })
                                    </section>
                                    <section>
                                        <label for="PurchasePONo" class="col-lg-3 control-label">Purchase PO No.</label>
                                        @Html.TextBoxFor(m => m.PurchasePONo, new { @id = "PurchasePONo", @class = "form-control", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.PurchasePONo, null, new { @class = "note-error color-red" })
                                    </section>
                                </div>
                                @*<div class="clearfix margin-bottom-20"></div>*@
                            </div>
                        </div>
                    </div>
                    <button id="btn-SubmitNewStock" type="submit" class="btn-u btn-u-primary btn-FloatRight">Submit</button>
                </div>
            </div>

            <div class="modal fade bs-example-modal-sm" id="AddNewStockLoading" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                    <img class="img-responsive" src="~/Images/ajax_loader.gif" alt="Loading ..." />
                </div>
            </div>
        }
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var UrlSubmitNewStock = "@Url.Action("AddNewStock", "Inventory")";
        var UrlProjectInfo = "@Url.Action("GetProjectInfo", "Inventory")";
        var UrlPartNoInfo = "@Url.Action("GetPartNoInfo", "Inventory")";
        var UrlContractList = "@Url.Action("ContractList", "ContList" )";
    </script>
    @Scripts.Render("~/bundles/JSPages");
}

Initiatives/Views/Inventory/Index.cshtml
@model Initiatives.Models.MainModel

@using (Ajax.BeginForm("Index", "Inventory", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace }, new { @class = "sky-form" }))
{
    <div class="container-fluid">
        <div id="RoleIds" class="hidden">@Model.RoleId</div>
        @Html.HiddenFor(m => m.OppContId)
        <div class="row">
            <div class="clearfix margin-bottom-10"></div>
            <div class="margin-bottom-25">
                @*@if (Model.RoleId == "R04" || Model.RoleId == "R02" || Model.RoleId == "R09")
                {*@
                    <button id="bAddNewReq" onclick="location.href = '@Url.Action("AddNewReq","Inventory")'" type="button" class="btn-u btn-u-primary">Add New Request</button>
                    <button id="bAddNewStock" onclick="location.href = '@Url.Action("AddNewStock","Inventory")'" type="button" class="btn-u btn-u-primary">Add New Stock</button>
                @*}*@
            </div>
            <div class="dataTable_wrapper">
                <table class="table table-striped table-bordered table-hover wrapper" id="InventorySummaryTable">
                    <thead>
                        <tr>
                            <th class="never"></th>
                            @*<th class="all"></th>*@
                            <th class="all">Material Code</th>
                            <th class="all">Material Description</th>
                            <th class="desktop">Available Balance</th>
                            <th class="desktop">Balance Reserved</th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.InventoryListTable)
                    {
                        <tr id="clickHere">
                            <td class="hide never">@Html.DisplayFor(modelItem => item.PartNo)</td>
                            @*<td class="all"></td>*@
                            <td class="all">@Html.DisplayFor(modelItem => item.MaterialCode)</td>
                            <td class="all">@Html.DisplayFor(modelItem => item.MaterialDesc)</td>
                            <td class="desktop">@Html.DisplayFor(modelItem => item.AvailableBalance)</td>
                            <td class="desktop">@Html.DisplayFor(modelItem => item.BalanceReserved)</td>
                        </tr>
                    }
                </table>
            </div>
            <!--End Basic Table-->
        </div>
    </div>
}

@section scripts {
    <script type="text/javascript">
        var InventorySummaryTable;
        var URLInvInfo = "@Url.Action("InventoryInfo","Inventory")";
        var UrlCheckInvDetails = "@Url.Action("CheckInvInfo","Inventory")"
    </script>
    @Scripts.Render("~/bundles/JSPages");
}