Initiatives/Controllers/TNIListController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Initiatives.Models;
using System.Net.Mail;
using System.Diagnostics;
using System.Data;
using Initiatives.Controllers;
using System.IO;
using RazorEngine;
using RazorEngine.Templating;
using System.Text;
using Newtonsoft.Json;
using System.Net;
using System.Globalization;

namespace Initiatives.Controllers
{
    public class TNIListController : Controller
    {
        private OpportunityManagementEntities db = new OpportunityManagementEntities();

        public ActionResult CreateTNI()
        {
            return View();
        }

    }
}

Initiatives/Views/TNIList/CreateTNI.cshtml
@{ Layout = "~/Views/Shared/_MainLayout.cshtml"; }
@model Initiatives.Models.MainModel

<div class="container-fluid">
    <div class="clearfix margin-bottom-30"></div>
    <button class="btn-u btn-success margin-bottom-25" type="button" onclick="location.href = '@Url.Action("ContractList", "ContList")'">
        <i class="fa fa-tags"></i> Back
    </button>
    <div class="panel panel-u margin-bottom-20">
        <div class="panel-heading margin-bottom-10">
            <h3 class="panel-title"><i class="fa fa-user"></i>Add New TNI</h3>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("CreateTNI", "TNIList", FormMethod.Post, new { @id = "sky-form", @class = "sky-form" }))
            {
                <div class="shadow-wrapper">
                    <div class="tag-box tag-box-v1 box-shadow shadow-effect-2">
                        <div class="row">
                            <div class="container">
                                <h4><b>General Informations</b></h4>
                            </div>
                            <div class="clearfix margin-bottom-10"></div>
                            <div class="col-md-6">
                                <section>
                                    <label for="name" class="col-lg-3 control-label">Contract No.</label>
                                    <label class="select">
                                        @Html.DropDownListFor(m => m.OppoListDetail.CustId, (IEnumerable<SelectListItem>)ViewBag.Customerlist, new { @id = "Customer", @class = "form-control-static" })
                                    </label>
                                </section>
                                <section>
                                    @Html.LabelFor(m => m.OppoListDetail.OpportunityName, "Supplier Name", new { @class = "col-lg-3 control-label" })
                                    @Html.TextBoxFor(m => m.OppoListDetail.OpportunityName, new { @id = "SupplierName", @class = "form-control", @type = "text" })
                                    <label class="col-lg-3 control-label"></label>@Html.ValidationMessageFor(m => m.OppoListDetail.OpportunityName, null, new { @class = "note-error color-red" })
                                </section>
                                <section>
                                    <label for="TestingDate" class="col-lg-3 control-label">Testing Date</label>
                                    <label class="col-lg-offset-5 input">
                                        <i class="icon-append fa fa-calendar"></i>
                                        @*<input name="ProposalDueDate" id="ProposalDueDate" class="datepicker" type="text" placeholder="@ViewData["ProposalDueDate"]" />*@
                                        @Html.TextBoxFor(m => m.OppoListDetail.StartDate, "{0:dd/MM/yyyy}", new { @id = "TestingDate", @class = "datepicker", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.OppoListDetail.StartDate, null, new { @class = "note-error color-red" })
                                    </label>
                                </section>
                                <section>
                                    <label for="ProductDescription" class="col-lg-3 control-label">Product Description</label>
                                    <label class="col-lg-offset-5 textarea textarea-resizable">
                                        @Html.TextAreaFor(m => m.OppoListDetail.Description, 3, 1, new { @id = "ProductDescription" })
                                    </label>
                                    <label class="col-lg-3 control-label"></label>
                                    @Html.ValidationMessageFor(m => m.OppoListDetail.Description, null, new { @class = "note-error color-red" })
                                </section>
                                <section>
                                    <label for="DateOfAcceptance" class="col-lg-3 control-label">Date of Acceptance</label>
                                    <label class="col-lg-offset-5 input">
                                        <i class="icon-append fa fa-calendar"></i>
                                        @Html.TextBoxFor(m => m.OppoListDetail.StartDate, "{0:dd/MM/yyyy}", new { @id = "DateOfAcceptance", @class = "datepicker", @type = "text" })
                                        <label class="col-lg-3 control-label"></label>
                                        @Html.ValidationMessageFor(m => m.OppoListDetail.StartDate, null, new { @class = "note-error color-red" })
                                    </label>
                                </section>
                            </div>
                            <div class="col-md-6">
                                <section>
                                    <label class="col-lg-3 control-label">File Description</label>
                                    <label class="col-lg-offset-5 textarea textarea-resizable">
                                        @Html.TextAreaFor(m => m.FileDescription, 3, 1, new { @id = "POD_FileDescription" })
                                    </label>
                                    <label class="col-lg-3 control-label"></label>
                                    @Html.ValidationMessageFor(m => m.FileDescription, null, new { @class = "note-error color-red" })
                                </section>
                                <section>
                                    <label class="col-lg-3 control-label">Acceptance Certificate Slip</label>
                                    <label class="col-lg-7 input input-file" for="file">
                                        <div class="button">@Html.TextBoxFor(m => m.file, null, new { @name = "file", @type = "file", @onchange = "this.parentNode.nextSibling.value = this.value" }) Browse</div><input class="width-83" id="TNI_Files" type="text" readonly>
                                    </label>
                                    @Html.ValidationMessageFor(m => m.file, null, new { @class = "note-error color-red" })
                                </section>
                            </div>
                            @if (Model.RoleId == "R02" || Model.RoleId == "R04" || Model.RoleId == "R09")
                            {
                                <div class="row btn-FloatRight">
                                    <button id="VerifyPODetails" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Save changes</button>
                                </div>
                            }
                            <div class="clearfix margin-bottom-20"></div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn-u btn-u-primary btn-FloatRight">Submit</button>
            }
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            //debugger;
            $.validator.addMethod('date',
            function (value, element) {
                if (this.optional(element)) {
                    return true;
                }

                var ok = true;
                try {
                    $.datepicker.parseDate('dd/mm/yy', value);
                }
                catch (err) {
                    ok = false;
                }
                return ok;
            });

            $(".datepicker").datepicker({
                dateFormat: 'dd/mm/yy',
                prevText: '<i class="fa fa-angle-left"></i>',
                nextText: '<i class="fa fa-angle-right"></i>'
            });
        });
    </script>
}

Initiatives/Views/TNIList/Invitation.cshtml
@model Initiatives.Models.MainModel

<div class="clearfix margin-bottom-10"></div>
@using (Html.BeginForm("Invitation", "TNIList", FormMethod.Post, new { @id = "Invitation", @class = "sky-form", @enctype = "multipart/form-data" }))
{
    <div class="shadow-wrapper">
        <div class="tag-box tag-box-v1 box-shadow shadow-effect-2">
            <div class="row">
                <div class="container">
                    <h4><b>Invitation Details</b></h4>
                </div>
                <div class="clearfix margin-bottom-10"></div>
                <div class="col-md-6">
                    @Html.HiddenFor(m => m.CreateByUserId)
                    @Html.HiddenFor(m => m.OppContId)
                    @Html.HiddenFor(m => m.POId)
                    @Html.HiddenFor(m => m.RoleId)
                    <section>
                        @Html.LabelFor(m => m.TNIDetailObject.TnINo, "T&I  Number", new { @class = "col-lg-3 control-label" })
                        @Html.TextBoxFor(m => m.TNIDetailObject.TnINo, new { @id = "TnINo", @class = "form-control", @type = "text" })
                        <label class="col-lg-3 control-label"></label>
                        @Html.ValidationMessageFor(m => m.TNIDetailObject.TnINo, null, new { @class = "note-error color-red" })
                    </section>
                    <section>
                        <label for="TNI_TestDate" class="col-lg-3 control-label">T&amp;I Date</label>
                        <label class="col-lg-offset-5 input">
                            <i class="icon-append fa fa-calendar"></i>
                            @Html.TextBoxFor(m => m.TNIDetailObject.TestDate, "{0:dd/MM/yyyy}", new { @id = "TNI_TestDate", @class = "datepicker", @type = "text" })
                        </label>
                        <label class="col-lg-3 control-label"></label>
                        @Html.ValidationMessageFor(m => m.TNIDetailObject.TestDate, null, new { @class = "note-error color-red" })
                    </section>
                    <section>
                        <label for="TNI_Time" class="col-lg-3 control-label">T&amp;I Time</label>
                        @Html.TextBoxFor(m => m.TNIDetailObject.StartTime, new { @id = "TNI_StartTime", @class = "form-control", @type = "text" }) - 
                        @Html.TextBoxFor(m => m.TNIDetailObject.EndTime, new { @id = "TNI_EndTime", @class = "form-control", @type = "text" })
                        <label class="col-lg-3 control-label"></label>
                        @Html.ValidationMessageFor(m => m.TNIDetailObject.StartTime, null, new { @class = "note-error color-red" })
                        @Html.ValidationMessageFor(m => m.TNIDetailObject.EndTime, null, new { @class = "note-error color-red" })
                    </section>
                    <section>
                        <label for="TNI_Venue" class="col-lg-3 control-label">T&amp;I Venue</label>
                        @Html.TextBoxFor(m => m.TNIDetailObject.Venue, new { @id = "TNI_Venue", @class = "form-control", @type = "text" })
                        <label class="col-lg-3 control-label"></label>
                        @Html.ValidationMessageFor(m => m.TNIDetailObject.Venue, null, new { @class = "note-error color-red" })
                    </section>
                </div>
                <div class="col-md-6">
                    <section>
                        <label class="col-lg-3 control-label">Internal Check List</label>
                        <label class="col-lg-7 input input-file" for="IntCheckList">
                            <div class="button">@Html.TextBoxFor(m => m.IntCheckList, null, new { @name = "IntCheckList", @type = "file", @onchange = "this.parentNode.nextSibling.value = this.value" }) Browse</div><input class="width-83" id="IntCheckList_Files" type="text" readonly>
                        </label>
                        @Html.ValidationMessageFor(m => m.IntCheckList, null, new { @class = "note-error color-red" })
                    </section>
                    <section>
                        <label class="col-lg-3 control-label">Invitation Letter</label>
                        <label class="col-lg-7 input input-file" for="InviLetter">
                            <div class="button">@Html.TextBoxFor(m => m.InviLetter, null, new { @name = "InviLetter", @type = "file", @onchange = "this.parentNode.nextSibling.value = this.value" }) Browse</div><input class="width-83" id="InviLetter_Files" type="text" readonly>
                        </label>
                        @Html.ValidationMessageFor(m => m.InviLetter, null, new { @class = "note-error color-red" })
                    </section>
                    <section>
                        <label for="userName" class="col-lg-3 control-label">Assign To</label>
                        <label class="select">
                            @Html.DropDownListFor(m => m.OppoListDetail.AccManagerId, (IEnumerable<SelectListItem>)ViewBag.Managerlist, new { @id = "AssignTo", @class = "form-control-static" })
                        </label>
                    </section>
                </div>
            </div>
        </div>
        <div class="clearfix margin-bottom-10"></div>
        <div class="tag-box tag-box-v1 box-shadow shadow-effect-2">
            <div class="row container-fluid">
                <div class="container">
                    <h4><b>PO Items</b></h4>
                    @if (Model.POItemListObject.Count == 0)
                    {
                        <div class="btn-FloatRight">
                            <button id="AddPOItem" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Add PO Item</button>
                        </div>
                    }
                </div>
                <div class="clearfix margin-bottom-10"></div>
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover wrapper" id="POItems4TnITable">
                        <thead>
                            <tr>
                                <th class="all">PO No.</th>
                                <th class="all">Material No.</th>
                                <th class="all">Description</th>
                                <th class="desktop">Quantity</th>
                                @if (Model.POItemListObject.Count == 0)
                                {
                                    <th class="desktop"></th>
                                }
                            </tr>
                        </thead>
                        @if (Model.POItemListObject.Count != 0)
                        {
                            foreach (var item in Model.POItemListObject)
                            {
                                <tr>
                                    <td>
                                        <label class="select">
                                            @Html.DropDownListFor(m => item.POId, (IEnumerable<SelectListItem>)ViewBag.PONoList, new { @id = "PONolist", @class = "form-control-static" })
                                        </label>
                                    </td>
                                    <td>
                                        <label class="select">
                                            @Html.DropDownListFor(m => item.ItemsId, (IEnumerable<SelectListItem>)ViewBag.MaterialNoList, new { @id = "MaterialNoList", @class = "form-control-static" })
                                        </label>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td>
                                    <label class="select">
                                        @Html.DropDownListFor(m => m.POItemsObject.POId, (IEnumerable<SelectListItem>)ViewBag.PONoList, new { @id = "PONolist", @class = "form-control-static" })
                                    </label>
                                </td>
                                <td>
                                    <label class="select">
                                        @Html.DropDownListFor(m => m.POItemsObject.MaterialNo, (IEnumerable<SelectListItem>)ViewBag.MaterialNoList, new { @id = "MaterialNoList", @class = "form-control-static" })
                                    </label>
                                </td>
                                <td>
                                    @Html.DisplayFor(m => m.POItemsObject.Description)
                                </td>
                                <td>
                                    <input class="form-control form-control-doc desktop" type="text" name="Quantity" />
                                </td>
                                <td></td>
                                <td></td>
                                @*<td><button id="AddPOItem" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Add</button></td>*@
                                <td><button id="RemovePOItem" type="submit" class="btn-u btn-u-primary">Delete</button></td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
        <div class="clearfix margin-bottom-10"></div>
        @if (Model.RoleId == "R02" || Model.RoleId == "R04" || Model.RoleId == "R09")
        {
            <div class="row btn-FloatRight">
                <button id="SubmitInvitation" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Submit</button>
            </div>
        }
        @if (Model.RoleId == "R02" || Model.RoleId == "R04" || Model.RoleId == "R09")
        {
            <div class="row btn-FloatRight">
                <button id="AcceptInvitation" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Accept</button>
                <button id="RejectInvitation" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Reject</button>
            </div>
        }
    </div>
    <div class="modal fade bs-example-modal-sm" id="PODetailsLoading" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <img class="img-responsive" src="~/Images/ajax_loader.gif" alt="Loading ..." />
        </div>
    </div>
    <div class="modal fade" id="AcceptInviModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row">
                        Please enter the following
                        <section>
                            <label for="userName" class="col-lg-3 control-label">Assign To</label>
                            <label class="select">
                                @Html.DropDownListFor(m => m.OppoListDetail.AccManagerId, (IEnumerable<SelectListItem>)ViewBag.Managerlist, new { @id = "AssignTo", @class = "form-control-static" })
                            </label>
                        </section>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-u btn-u-default" data-dismiss="modal">Close</button>
                    <button id="SubmitAcceptInvi" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="RejectInviModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row">
                        Please enter the following
                        <section>
                            <label for="userName" class="col-lg-3 control-label">Assign To</label>
                            <label class="select">
                                @Html.DropDownListFor(m => m.OppoListDetail.AccManagerId, (IEnumerable<SelectListItem>)ViewBag.Managerlist, new { @id = "AssignTo", @class = "form-control-static" })
                            </label>
                        </section>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-u btn-u-default" data-dismiss="modal">Close</button>
                    <button id="SubmitAcceptInvi" type="submit" class="btn-SaveChanges btn-u btn-u-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
}

Initiatives/Views/TNIList/ViewTNI.cshtml
@{ Layout = "~/Views/Shared/_MainLayout.cshtml"; }
@model Initiatives.Models.MainModel

<div class="container-fluid">
    <div class="clearfix margin-bottom-30"></div>
    <button class="btn-u btn-success margin-bottom-25" type="button" onclick="location.href = '@Url.Action("ViewContract", "ContList")'">
        <i class="fa fa-tags"></i> Back
    </button>
    <!-- Tab v2 -->
    <div class="tab-v2">
        <ul class="nav nav-tabs">
            <li class="active navbar-height"><a href="#Invitation-1" data-toggle="tab"><h4>Invitation</h4></a></li>
            <li class="navbar-height"><a href="#Result-1" data-toggle="tab"><h4>Result</h4></a></li>
            <li class="navbar-height"><a href="#Comply-1" data-toggle="tab"><h4>Comply</h4></a></li>
            <li class="navbar-height"><a href="#Improvement-1" data-toggle="tab"><h4>Improvement</h4></a></li>
            <li class="navbar-height"><a href="#NonComply-1" data-toggle="tab"><h4>Non Comply</h4></a></li>
        </ul>
        <div class="tab-content">
            @*<div class="tab-pane fade in active" id="info-1">
                </div>*@
            <div class="tab-pane fade in active" id="Invitation-1">
                @{ Html.RenderAction("Invitation", "TNIList", new { PoId = Model.POId }); }
            </div>
            <div class="tab-pane fade in" id="Result-1">
                @{ Html.RenderAction("Result", "TNIList"); }
            </div>
            <div class="tab-pane fade in" id="Comply-1">
                @{ Html.RenderAction("Comply", "TNIList"); }
            </div>
            <div class="tab-pane fade in" id="Improvement-1">
                @{ Html.RenderAction("Improvement", "TNIList"); }
            </div>
            <div class="tab-pane fade in" id="NonComply-1">
                @{ Html.RenderAction("NonComply", "TNIList"); }
            </div>
        </div>
    </div>
    <!-- End Tab v2 -->
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
        });
    </script>
}